name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm update
          npm install

      - name: Lint with eslint
        run: eslint src --ext ts,tsx --report-unused-disable-directives --max-warnings 0
        
      - name: Run unit test with jest
        run: npm test
